services:
  web:
    build: .
    container_name: ecommerce_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      MYSQLHOST: db
      MYSQLPORT: 3306
      MYSQLDATABASE: ecommerce
      MYSQLUSER: ecommerce
      MYSQLPASSWORD: ecommerce123

  db:
    image: mysql:8.0
    container_name: ecommerce_db
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: ecommerce123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Auto-import do dump
      - ./dados.sql:/docker-entrypoint-initdb.d/01-dados.sql:ro

volumes:
  db_data: